// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcorg

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	AppID       uuid.UUID          `json:"app_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Ephemeral   bool               `json:"ephemeral"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
}

type GroupMember struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	AppID   uuid.UUID `json:"app_id"`
}

type OrgInvitation struct {
	ID         uuid.UUID          `json:"id"`
	OrgID      uuid.UUID          `json:"org_id"`
	Email      string             `json:"email"`
	Role       string             `json:"role"`
	Token      string             `json:"token"`
	ExpiresAt  time.Time          `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  time.Time          `json:"created_at"`
}

type OrgMember struct {
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	JoinedAt  time.Time   `json:"joined_at"`
}

type Organization struct {
	ID          uuid.UUID          `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	OwnerUserID uuid.UUID          `json:"owner_user_id"`
	Plan        string             `json:"plan"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	SuspendedAt pgtype.Timestamptz `json:"suspended_at"`
}

type Outbox struct {
	ID          uuid.UUID          `json:"id"`
	AggregateID uuid.UUID          `json:"aggregate_id"`
	EventType   string             `json:"event_type"`
	Payload     json.RawMessage    `json:"payload"`
	CreatedAt   time.Time          `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type Role struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	CreatedAt   time.Time `json:"created_at"`
}
