// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcorg

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec

INSERT INTO group_members (group_id, user_id, app_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	AppID   uuid.UUID `json:"app_id"`
}

// ─── group_members ──────────────────────────────────────────────────────────
func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.AppID)
	return err
}

const addOrgMember = `-- name: AddOrgMember :exec

INSERT INTO org_members (org_id, user_id, role, invited_by, joined_at)
VALUES ($1, $2, $3, $4, $5)
`

type AddOrgMemberParams struct {
	OrgID     uuid.UUID   `json:"org_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Role      string      `json:"role"`
	InvitedBy pgtype.UUID `json:"invited_by"`
	JoinedAt  time.Time   `json:"joined_at"`
}

// ─── org_members ────────────────────────────────────────────────────────────
func (q *Queries) AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error {
	_, err := q.db.Exec(ctx, addOrgMember,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
		arg.JoinedAt,
	)
	return err
}

const createGroup = `-- name: CreateGroup :exec

INSERT INTO groups (id, org_id, app_id, name, description, ephemeral, expires_at, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateGroupParams struct {
	ID          uuid.UUID          `json:"id"`
	OrgID       uuid.UUID          `json:"org_id"`
	AppID       uuid.UUID          `json:"app_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	Ephemeral   bool               `json:"ephemeral"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   time.Time          `json:"created_at"`
}

// ─── groups ─────────────────────────────────────────────────────────────────
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) error {
	_, err := q.db.Exec(ctx, createGroup,
		arg.ID,
		arg.OrgID,
		arg.AppID,
		arg.Name,
		arg.Description,
		arg.Ephemeral,
		arg.ExpiresAt,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createInvitation = `-- name: CreateInvitation :exec

INSERT INTO org_invitations (id, org_id, email, role, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateInvitationParams struct {
	ID        uuid.UUID `json:"id"`
	OrgID     uuid.UUID `json:"org_id"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

// ─── org_invitations ────────────────────────────────────────────────────────
func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) error {
	_, err := q.db.Exec(ctx, createInvitation,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.Role,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createOrganization = `-- name: CreateOrganization :exec

INSERT INTO organizations (id, name, slug, owner_user_id, plan, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateOrganizationParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	OwnerUserID uuid.UUID `json:"owner_user_id"`
	Plan        string    `json:"plan"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// ─── organizations ───────────────────────────────────────────────────────────
func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.Exec(ctx, createOrganization,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.OwnerUserID,
		arg.Plan,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRole = `-- name: CreateRole :exec

INSERT INTO roles (id, org_id, name, permissions, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	OrgID       uuid.UUID `json:"org_id"`
	Name        string    `json:"name"`
	Permissions []string  `json:"permissions"`
	CreatedAt   time.Time `json:"created_at"`
}

// ─── roles ──────────────────────────────────────────────────────────────────
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Permissions,
		arg.CreatedAt,
	)
	return err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, org_id, app_id, name, description, ephemeral, expires_at, created_by, created_at
FROM groups
WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.AppID,
		&i.Name,
		&i.Description,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, org_id, email, role, token, expires_at, accepted_at, created_at
FROM org_invitations
WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (OrgInvitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i OrgInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Role,
		&i.Token,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgMember = `-- name: GetOrgMember :one
SELECT org_id, user_id, role, invited_by, joined_at
FROM org_members
WHERE org_id = $1 AND user_id = $2
`

type GetOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error) {
	row := q.db.QueryRow(ctx, getOrgMember, arg.OrgID, arg.UserID)
	var i OrgMember
	err := row.Scan(
		&i.OrgID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, slug, owner_user_id, plan, created_at, updated_at, suspended_at
FROM organizations
WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, owner_user_id, plan, created_at, updated_at, suspended_at
FROM organizations
WHERE slug = $1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.OwnerUserID,
		&i.Plan,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, org_id, name, permissions, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at
FROM outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
`

type GetUnpublishedOutboxEventsRow struct {
	ID          uuid.UUID       `json:"id"`
	AggregateID uuid.UUID       `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]GetUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i GetUnpublishedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO outbox (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxEventParams struct {
	AggregateID uuid.UUID       `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
}

// ─── outbox ─────────────────────────────────────────────────────────────────
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const listExpiredGroups = `-- name: ListExpiredGroups :many
SELECT id, org_id, app_id, name, description, ephemeral, expires_at, created_by, created_at
FROM groups
WHERE ephemeral = true AND expires_at IS NOT NULL AND expires_at < $1
`

func (q *Queries) ListExpiredGroups(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Group, error) {
	rows, err := q.db.Query(ctx, listExpiredGroups, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.Ephemeral,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT group_id, user_id, app_id
FROM group_members
WHERE group_id = $1
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupMember{}
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(&i.GroupID, &i.UserID, &i.AppID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByOrg = `-- name: ListGroupsByOrg :many
SELECT id, org_id, app_id, name, description, ephemeral, expires_at, created_by, created_at
FROM groups
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListGroupsByOrg(ctx context.Context, orgID uuid.UUID) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AppID,
			&i.Name,
			&i.Description,
			&i.Ephemeral,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgMembers = `-- name: ListOrgMembers :many
SELECT org_id, user_id, role, invited_by, joined_at
FROM org_members
WHERE org_id = $1
ORDER BY joined_at
`

func (q *Queries) ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]OrgMember, error) {
	rows, err := q.db.Query(ctx, listOrgMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrgMember{}
	for rows.Next() {
		var i OrgMember
		if err := rows.Scan(
			&i.OrgID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByOrg = `-- name: ListRolesByOrg :many
SELECT id, org_id, name, permissions, created_at
FROM roles
WHERE org_id = $1
ORDER BY name
`

func (q *Queries) ListRolesByOrg(ctx context.Context, orgID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Permissions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE org_invitations SET accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeOrgMember = `-- name: RemoveOrgMember :exec
DELETE FROM org_members
WHERE org_id = $1 AND user_id = $2
`

type RemoveOrgMemberParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error {
	_, err := q.db.Exec(ctx, removeOrgMember, arg.OrgID, arg.UserID)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET
    name       = $2,
    plan       = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Plan      string    `json:"plan"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.ID,
		arg.Name,
		arg.Plan,
		arg.UpdatedAt,
	)
	return err
}
