// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcorg

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ─── group_members ──────────────────────────────────────────────────────────
	AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error
	// ─── org_members ────────────────────────────────────────────────────────────
	AddOrgMember(ctx context.Context, arg AddOrgMemberParams) error
	// ─── groups ─────────────────────────────────────────────────────────────────
	CreateGroup(ctx context.Context, arg CreateGroupParams) error
	// ─── org_invitations ────────────────────────────────────────────────────────
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) error
	// ─── organizations ───────────────────────────────────────────────────────────
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	// ─── roles ──────────────────────────────────────────────────────────────────
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	DeleteGroup(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error)
	GetInvitationByToken(ctx context.Context, token string) (OrgInvitation, error)
	GetOrgMember(ctx context.Context, arg GetOrgMemberParams) (OrgMember, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error)
	GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]GetUnpublishedOutboxEventsRow, error)
	// ─── outbox ─────────────────────────────────────────────────────────────────
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListExpiredGroups(ctx context.Context, expiresAt pgtype.Timestamptz) ([]Group, error)
	ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupMember, error)
	ListGroupsByOrg(ctx context.Context, orgID uuid.UUID) ([]Group, error)
	ListOrgMembers(ctx context.Context, orgID uuid.UUID) ([]OrgMember, error)
	ListRolesByOrg(ctx context.Context, orgID uuid.UUID) ([]Role, error)
	MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error
	RemoveOrgMember(ctx context.Context, arg RemoveOrgMemberParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
}

var _ Querier = (*Queries)(nil)
