// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcnotification

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Notification struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	AppID          uuid.UUID          `json:"app_id"`
	GroupID        pgtype.UUID        `json:"group_id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	Title          string             `json:"title"`
	Body           string             `json:"body"`
	Data           json.RawMessage    `json:"data"`
	DeliveryStatus string             `json:"delivery_status"`
	ReadAt         pgtype.Timestamptz `json:"read_at"`
	CreatedAt      time.Time          `json:"created_at"`
}

type NotificationPreference struct {
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Channel   string    `json:"channel"`
	EventType string    `json:"event_type"`
	Enabled   bool      `json:"enabled"`
	UpdatedAt time.Time `json:"updated_at"`
}
