// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcnotification

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, app_id, group_id, org_id, title, body, data, delivery_status, read_at, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.GroupID,
		&i.OrgID,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.DeliveryStatus,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT user_id, app_id, channel, event_type, enabled, updated_at
FROM notification_preferences
WHERE user_id = $1 AND app_id = $2
`

type GetNotificationPreferencesParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) GetNotificationPreferences(ctx context.Context, arg GetNotificationPreferencesParams) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.AppID,
			&i.Channel,
			&i.EventType,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPreferenceEnabled = `-- name: GetPreferenceEnabled :one
SELECT enabled FROM notification_preferences
WHERE user_id = $1 AND app_id = $2 AND channel = $3
  AND (event_type = $4 OR event_type = '*')
ORDER BY event_type DESC  -- exact match wins over wildcard
LIMIT 1
`

type GetPreferenceEnabledParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Channel   string    `json:"channel"`
	EventType string    `json:"event_type"`
}

func (q *Queries) GetPreferenceEnabled(ctx context.Context, arg GetPreferenceEnabledParams) (bool, error) {
	row := q.db.QueryRow(ctx, getPreferenceEnabled,
		arg.UserID,
		arg.AppID,
		arg.Channel,
		arg.EventType,
	)
	var enabled bool
	err := row.Scan(&enabled)
	return enabled, err
}

const insertNotification = `-- name: InsertNotification :exec

INSERT INTO notifications (id, user_id, app_id, group_id, org_id, title, body, data, delivery_status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertNotificationParams struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	AppID          uuid.UUID       `json:"app_id"`
	GroupID        pgtype.UUID     `json:"group_id"`
	OrgID          pgtype.UUID     `json:"org_id"`
	Title          string          `json:"title"`
	Body           string          `json:"body"`
	Data           json.RawMessage `json:"data"`
	DeliveryStatus string          `json:"delivery_status"`
	CreatedAt      time.Time       `json:"created_at"`
}

// ─── notifications ────────────────────────────────────────────────────────────
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) error {
	_, err := q.db.Exec(ctx, insertNotification,
		arg.ID,
		arg.UserID,
		arg.AppID,
		arg.GroupID,
		arg.OrgID,
		arg.Title,
		arg.Body,
		arg.Data,
		arg.DeliveryStatus,
		arg.CreatedAt,
	)
	return err
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, app_id, group_id, org_id, title, body, data, delivery_status, read_at, created_at
FROM notifications
WHERE user_id = $1 AND app_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListNotificationsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser,
		arg.UserID,
		arg.AppID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.GroupID,
			&i.OrgID,
			&i.Title,
			&i.Body,
			&i.Data,
			&i.DeliveryStatus,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now() WHERE id = $1 AND read_at IS NULL
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationRead, id)
	return err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :exec
UPDATE notifications SET delivery_status = $2 WHERE id = $1
`

type UpdateNotificationStatusParams struct {
	ID             uuid.UUID `json:"id"`
	DeliveryStatus string    `json:"delivery_status"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error {
	_, err := q.db.Exec(ctx, updateNotificationStatus, arg.ID, arg.DeliveryStatus)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :exec

INSERT INTO notification_preferences (user_id, app_id, channel, event_type, enabled, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (user_id, app_id, channel, event_type)
DO UPDATE SET enabled = EXCLUDED.enabled, updated_at = now()
`

type UpsertNotificationPreferenceParams struct {
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Channel   string    `json:"channel"`
	EventType string    `json:"event_type"`
	Enabled   bool      `json:"enabled"`
}

// ─── notification_preferences ─────────────────────────────────────────────────
func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error {
	_, err := q.db.Exec(ctx, upsertNotificationPreference,
		arg.UserID,
		arg.AppID,
		arg.Channel,
		arg.EventType,
		arg.Enabled,
	)
	return err
}
