// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcnotification

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetNotificationPreferences(ctx context.Context, arg GetNotificationPreferencesParams) ([]NotificationPreference, error)
	GetPreferenceEnabled(ctx context.Context, arg GetPreferenceEnabledParams) (bool, error)
	// ─── notifications ────────────────────────────────────────────────────────────
	InsertNotification(ctx context.Context, arg InsertNotificationParams) error
	ListNotificationsForUser(ctx context.Context, arg ListNotificationsForUserParams) ([]Notification, error)
	MarkNotificationRead(ctx context.Context, id uuid.UUID) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
	// ─── notification_preferences ─────────────────────────────────────────────────
	UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) error
}

var _ Querier = (*Queries)(nil)
