// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcidentity

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ArtifactStorage struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DeviceToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Platform  string    `json:"platform"`
	TokenType string    `json:"token_type"`
	Token     string    `json:"token"`
	DeviceID  string    `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Outbox struct {
	ID          uuid.UUID          `json:"id"`
	AggregateID uuid.UUID          `json:"aggregate_id"`
	EventType   string             `json:"event_type"`
	Payload     json.RawMessage    `json:"payload"`
	CreatedAt   time.Time          `json:"created_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

type UserProfile struct {
	ID          uuid.UUID       `json:"id"`
	AppID       uuid.UUID       `json:"app_id"`
	DisplayName string          `json:"display_name"`
	AvatarUrl   string          `json:"avatar_url"`
	Bio         string          `json:"bio"`
	Location    string          `json:"location"`
	WebsiteUrl  string          `json:"website_url"`
	Settings    json.RawMessage `json:"settings"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
