// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcidentity

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error
	DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error
	GetArtifact(ctx context.Context, arg GetArtifactParams) (ArtifactStorage, error)
	GetDeviceTokensByUser(ctx context.Context, arg GetDeviceTokensByUserParams) ([]DeviceToken, error)
	GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]GetUnpublishedOutboxEventsRow, error)
	GetUserProfile(ctx context.Context, arg GetUserProfileParams) (UserProfile, error)
	// ─── outbox ──────────────────────────────────────────────────────────────────
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ArtifactStorage, error)
	MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
	// ─── artifact_storage ────────────────────────────────────────────────────────
	UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) error
	// ─── device_tokens ───────────────────────────────────────────────────────────
	UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error
	// ─── user_profiles ───────────────────────────────────────────────────────────
	UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
