// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlcidentity

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifact_storage
WHERE user_id = $1 AND app_id = $2 AND key = $3
`

type DeleteArtifactParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
	Key    string    `json:"key"`
}

func (q *Queries) DeleteArtifact(ctx context.Context, arg DeleteArtifactParams) error {
	_, err := q.db.Exec(ctx, deleteArtifact, arg.UserID, arg.AppID, arg.Key)
	return err
}

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens
WHERE app_id = $1 AND device_id = $2
`

type DeleteDeviceTokenParams struct {
	AppID    uuid.UUID `json:"app_id"`
	DeviceID string    `json:"device_id"`
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, deleteDeviceToken, arg.AppID, arg.DeviceID)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, user_id, app_id, key, value, created_at, updated_at
FROM artifact_storage
WHERE user_id = $1 AND app_id = $2 AND key = $3
`

type GetArtifactParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (ArtifactStorage, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.UserID, arg.AppID, arg.Key)
	var i ArtifactStorage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AppID,
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeviceTokensByUser = `-- name: GetDeviceTokensByUser :many
SELECT id, user_id, app_id, platform, token_type, token, device_id, created_at, updated_at
FROM device_tokens
WHERE user_id = $1 AND app_id = $2
`

type GetDeviceTokensByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) GetDeviceTokensByUser(ctx context.Context, arg GetDeviceTokensByUserParams) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, getDeviceTokensByUser, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceToken{}
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.Platform,
			&i.TokenType,
			&i.Token,
			&i.DeviceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedOutboxEvents = `-- name: GetUnpublishedOutboxEvents :many
SELECT id, aggregate_id, event_type, payload, created_at
FROM outbox
WHERE published_at IS NULL
ORDER BY created_at
LIMIT $1
`

type GetUnpublishedOutboxEventsRow struct {
	ID          uuid.UUID       `json:"id"`
	AggregateID uuid.UUID       `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
	CreatedAt   time.Time       `json:"created_at"`
}

func (q *Queries) GetUnpublishedOutboxEvents(ctx context.Context, limit int32) ([]GetUnpublishedOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnpublishedOutboxEventsRow{}
	for rows.Next() {
		var i GetUnpublishedOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT id, app_id, display_name, avatar_url, bio, location, website_url, settings, created_at, updated_at
FROM user_profiles
WHERE id = $1 AND app_id = $2
`

type GetUserProfileParams struct {
	ID    uuid.UUID `json:"id"`
	AppID uuid.UUID `json:"app_id"`
}

func (q *Queries) GetUserProfile(ctx context.Context, arg GetUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, arg.ID, arg.AppID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.Location,
		&i.WebsiteUrl,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec

INSERT INTO outbox (aggregate_id, event_type, payload)
VALUES ($1, $2, $3)
`

type InsertOutboxEventParams struct {
	AggregateID uuid.UUID       `json:"aggregate_id"`
	EventType   string          `json:"event_type"`
	Payload     json.RawMessage `json:"payload"`
}

// ─── outbox ──────────────────────────────────────────────────────────────────
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent, arg.AggregateID, arg.EventType, arg.Payload)
	return err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, user_id, app_id, key, value, created_at, updated_at
FROM artifact_storage
WHERE user_id = $1 AND app_id = $2
ORDER BY key
`

type ListArtifactsParams struct {
	UserID uuid.UUID `json:"user_id"`
	AppID  uuid.UUID `json:"app_id"`
}

func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ArtifactStorage, error) {
	rows, err := q.db.Query(ctx, listArtifacts, arg.UserID, arg.AppID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArtifactStorage{}
	for rows.Next() {
		var i ArtifactStorage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AppID,
			&i.Key,
			&i.Value,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox SET published_at = now()
WHERE id = $1
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE user_profiles
SET
    display_name = $3,
    avatar_url   = $4,
    bio          = $5,
    location     = $6,
    website_url  = $7,
    settings     = $8,
    updated_at   = $9
WHERE id = $1 AND app_id = $2
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID       `json:"id"`
	AppID       uuid.UUID       `json:"app_id"`
	DisplayName string          `json:"display_name"`
	AvatarUrl   string          `json:"avatar_url"`
	Bio         string          `json:"bio"`
	Location    string          `json:"location"`
	WebsiteUrl  string          `json:"website_url"`
	Settings    json.RawMessage `json:"settings"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.AppID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.Location,
		arg.WebsiteUrl,
		arg.Settings,
		arg.UpdatedAt,
	)
	return err
}

const upsertArtifact = `-- name: UpsertArtifact :exec

INSERT INTO artifact_storage (id, user_id, app_id, key, value, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, app_id, key)
DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = EXCLUDED.updated_at
`

type UpsertArtifactParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ─── artifact_storage ────────────────────────────────────────────────────────
func (q *Queries) UpsertArtifact(ctx context.Context, arg UpsertArtifactParams) error {
	_, err := q.db.Exec(ctx, upsertArtifact,
		arg.ID,
		arg.UserID,
		arg.AppID,
		arg.Key,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec

INSERT INTO device_tokens (id, user_id, app_id, platform, token_type, token, device_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (app_id, device_id)
DO UPDATE SET
    user_id    = EXCLUDED.user_id,
    platform   = EXCLUDED.platform,
    token_type = EXCLUDED.token_type,
    token      = EXCLUDED.token,
    updated_at = EXCLUDED.updated_at
`

type UpsertDeviceTokenParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	AppID     uuid.UUID `json:"app_id"`
	Platform  string    `json:"platform"`
	TokenType string    `json:"token_type"`
	Token     string    `json:"token"`
	DeviceID  string    `json:"device_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ─── device_tokens ───────────────────────────────────────────────────────────
func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.Exec(ctx, upsertDeviceToken,
		arg.ID,
		arg.UserID,
		arg.AppID,
		arg.Platform,
		arg.TokenType,
		arg.Token,
		arg.DeviceID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec

INSERT INTO user_profiles (id, app_id, display_name, avatar_url, bio, location, website_url, settings, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id, app_id)
DO UPDATE SET
    display_name = EXCLUDED.display_name,
    avatar_url   = EXCLUDED.avatar_url,
    bio          = EXCLUDED.bio,
    location     = EXCLUDED.location,
    website_url  = EXCLUDED.website_url,
    settings     = EXCLUDED.settings,
    updated_at   = EXCLUDED.updated_at
`

type UpsertUserProfileParams struct {
	ID          uuid.UUID       `json:"id"`
	AppID       uuid.UUID       `json:"app_id"`
	DisplayName string          `json:"display_name"`
	AvatarUrl   string          `json:"avatar_url"`
	Bio         string          `json:"bio"`
	Location    string          `json:"location"`
	WebsiteUrl  string          `json:"website_url"`
	Settings    json.RawMessage `json:"settings"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

// ─── user_profiles ───────────────────────────────────────────────────────────
func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile,
		arg.ID,
		arg.AppID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.Location,
		arg.WebsiteUrl,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
